/**
 * 单词精灵 - 小学英语词库
 * 按年级/单元组织，涵盖人教版PEP教材核心词汇
 */
const WORD_DB = {
    3: [ // 三年级
        { word: "cat", phonetic: "/kæt/", meaning: "猫", example: "I have a <em>cat</em>.", emoji: "🐱", unit: 1 },
        { word: "dog", phonetic: "/dɒɡ/", meaning: "狗", example: "The <em>dog</em> is cute.", emoji: "🐶", unit: 1 },
        { word: "duck", phonetic: "/dʌk/", meaning: "鸭子", example: "Look at the <em>duck</em>.", emoji: "🦆", unit: 1 },
        { word: "pig", phonetic: "/pɪɡ/", meaning: "猪", example: "The <em>pig</em> is fat.", emoji: "🐷", unit: 1 },
        { word: "bear", phonetic: "/beə/", meaning: "熊", example: "I see a <em>bear</em>.", emoji: "🐻", unit: 1 },
        { word: "red", phonetic: "/red/", meaning: "红色的", example: "The apple is <em>red</em>.", emoji: "🔴", unit: 2 },
        { word: "green", phonetic: "/ɡriːn/", meaning: "绿色的", example: "The tree is <em>green</em>.", emoji: "🟢", unit: 2 },
        { word: "blue", phonetic: "/bluː/", meaning: "蓝色的", example: "The sky is <em>blue</em>.", emoji: "🔵", unit: 2 },
        { word: "yellow", phonetic: "/ˈjeləʊ/", meaning: "黄色的", example: "The banana is <em>yellow</em>.", emoji: "🟡", unit: 2 },
        { word: "black", phonetic: "/blæk/", meaning: "黑色的", example: "I have a <em>black</em> pen.", emoji: "⚫", unit: 2 },
        { word: "white", phonetic: "/waɪt/", meaning: "白色的", example: "The snow is <em>white</em>.", emoji: "⚪", unit: 2 },
        { word: "one", phonetic: "/wʌn/", meaning: "一", example: "I have <em>one</em> book.", emoji: "1️⃣", unit: 3 },
        { word: "two", phonetic: "/tuː/", meaning: "二", example: "I see <em>two</em> birds.", emoji: "2️⃣", unit: 3 },
        { word: "three", phonetic: "/θriː/", meaning: "三", example: "There are <em>three</em> cats.", emoji: "3️⃣", unit: 3 },
        { word: "four", phonetic: "/fɔː/", meaning: "四", example: "I have <em>four</em> pens.", emoji: "4️⃣", unit: 3 },
        { word: "five", phonetic: "/faɪv/", meaning: "五", example: "I am <em>five</em> years old.", emoji: "5️⃣", unit: 3 },
        { word: "head", phonetic: "/hed/", meaning: "头", example: "Touch your <em>head</em>.", emoji: "👤", unit: 4 },
        { word: "hand", phonetic: "/hænd/", meaning: "手", example: "Clap your <em>hands</em>.", emoji: "✋", unit: 4 },
        { word: "eye", phonetic: "/aɪ/", meaning: "眼睛", example: "I have two <em>eyes</em>.", emoji: "👁️", unit: 4 },
        { word: "ear", phonetic: "/ɪə/", meaning: "耳朵", example: "I have two <em>ears</em>.", emoji: "👂", unit: 4 },
        { word: "nose", phonetic: "/nəʊz/", meaning: "鼻子", example: "Touch your <em>nose</em>.", emoji: "👃", unit: 4 },
        { word: "mouth", phonetic: "/maʊθ/", meaning: "嘴巴", example: "Open your <em>mouth</em>.", emoji: "👄", unit: 4 },
        { word: "foot", phonetic: "/fʊt/", meaning: "脚", example: "Stamp your <em>foot</em>.", emoji: "🦶", unit: 4 },
        { word: "body", phonetic: "/ˈbɒdi/", meaning: "身体", example: "This is my <em>body</em>.", emoji: "🧍", unit: 4 },
        { word: "cake", phonetic: "/keɪk/", meaning: "蛋糕", example: "I like <em>cake</em>.", emoji: "🎂", unit: 5 },
        { word: "bread", phonetic: "/bred/", meaning: "面包", example: "Have some <em>bread</em>.", emoji: "🍞", unit: 5 },
        { word: "egg", phonetic: "/eɡ/", meaning: "鸡蛋", example: "I eat an <em>egg</em>.", emoji: "🥚", unit: 5 },
        { word: "milk", phonetic: "/mɪlk/", meaning: "牛奶", example: "Drink some <em>milk</em>.", emoji: "🥛", unit: 5 },
        { word: "water", phonetic: "/ˈwɔːtə/", meaning: "水", example: "Can I have some <em>water</em>?", emoji: "💧", unit: 5 },
        { word: "fish", phonetic: "/fɪʃ/", meaning: "鱼", example: "I like <em>fish</em>.", emoji: "🐟", unit: 5 },
        { word: "rice", phonetic: "/raɪs/", meaning: "米饭", example: "Have some <em>rice</em>.", emoji: "🍚", unit: 5 },
        { word: "book", phonetic: "/bʊk/", meaning: "书", example: "I read a <em>book</em>.", emoji: "📖", unit: 6 },
        { word: "pen", phonetic: "/pen/", meaning: "钢笔", example: "This is my <em>pen</em>.", emoji: "🖊️", unit: 6 },
        { word: "bag", phonetic: "/bæɡ/", meaning: "书包", example: "I have a new <em>bag</em>.", emoji: "🎒", unit: 6 },
        { word: "ruler", phonetic: "/ˈruːlə/", meaning: "尺子", example: "I have a <em>ruler</em>.", emoji: "📐", unit: 6 },
        { word: "pencil", phonetic: "/ˈpensl/", meaning: "铅笔", example: "This is my <em>pencil</em>.", emoji: "✏️", unit: 6 },
        { word: "eraser", phonetic: "/ɪˈreɪzə/", meaning: "橡皮", example: "I need an <em>eraser</em>.", emoji: "🧽", unit: 6 },
    ],
    4: [ // 四年级
        { word: "classroom", phonetic: "/ˈklɑːsruːm/", meaning: "教室", example: "This is our <em>classroom</em>.", emoji: "🏫", unit: 1 },
        { word: "window", phonetic: "/ˈwɪndəʊ/", meaning: "窗户", example: "Open the <em>window</em>.", emoji: "🪟", unit: 1 },
        { word: "door", phonetic: "/dɔː/", meaning: "门", example: "Close the <em>door</em>.", emoji: "🚪", unit: 1 },
        { word: "floor", phonetic: "/flɔː/", meaning: "地板", example: "The <em>floor</em> is clean.", emoji: "🏠", unit: 1 },
        { word: "light", phonetic: "/laɪt/", meaning: "灯", example: "Turn on the <em>light</em>.", emoji: "💡", unit: 1 },
        { word: "desk", phonetic: "/desk/", meaning: "课桌", example: "The <em>desk</em> is new.", emoji: "🪑", unit: 1 },
        { word: "strong", phonetic: "/strɒŋ/", meaning: "强壮的", example: "My dad is <em>strong</em>.", emoji: "💪", unit: 2 },
        { word: "quiet", phonetic: "/ˈkwaɪət/", meaning: "安静的", example: "Please be <em>quiet</em>.", emoji: "🤫", unit: 2 },
        { word: "friendly", phonetic: "/ˈfrendli/", meaning: "友好的", example: "She is very <em>friendly</em>.", emoji: "🤝", unit: 2 },
        { word: "tall", phonetic: "/tɔːl/", meaning: "高的", example: "He is very <em>tall</em>.", emoji: "📏", unit: 2 },
        { word: "short", phonetic: "/ʃɔːt/", meaning: "矮的/短的", example: "The pencil is <em>short</em>.", emoji: "📐", unit: 2 },
        { word: "thin", phonetic: "/θɪn/", meaning: "瘦的/薄的", example: "She is <em>thin</em>.", emoji: "🧍‍♀️", unit: 2 },
        { word: "kitchen", phonetic: "/ˈkɪtʃɪn/", meaning: "厨房", example: "Mom is in the <em>kitchen</em>.", emoji: "🍳", unit: 3 },
        { word: "bedroom", phonetic: "/ˈbedruːm/", meaning: "卧室", example: "This is my <em>bedroom</em>.", emoji: "🛏️", unit: 3 },
        { word: "bathroom", phonetic: "/ˈbɑːθruːm/", meaning: "浴室", example: "Go to the <em>bathroom</em>.", emoji: "🚿", unit: 3 },
        { word: "living", phonetic: "/ˈlɪvɪŋ/", meaning: "起居的", example: "This is the <em>living</em> room.", emoji: "🛋️", unit: 3 },
        { word: "phone", phonetic: "/fəʊn/", meaning: "电话", example: "Answer the <em>phone</em>.", emoji: "📱", unit: 3 },
        { word: "sofa", phonetic: "/ˈsəʊfə/", meaning: "沙发", example: "Sit on the <em>sofa</em>.", emoji: "🛋️", unit: 3 },
        { word: "beef", phonetic: "/biːf/", meaning: "牛肉", example: "I like <em>beef</em>.", emoji: "🥩", unit: 4 },
        { word: "chicken", phonetic: "/ˈtʃɪkɪn/", meaning: "鸡肉", example: "Have some <em>chicken</em>.", emoji: "🍗", unit: 4 },
        { word: "noodle", phonetic: "/ˈnuːdl/", meaning: "面条", example: "I'd like some <em>noodles</em>.", emoji: "🍜", unit: 4 },
        { word: "soup", phonetic: "/suːp/", meaning: "汤", example: "The <em>soup</em> is hot.", emoji: "🍲", unit: 4 },
        { word: "vegetable", phonetic: "/ˈvedʒtəbl/", meaning: "蔬菜", example: "Eat your <em>vegetables</em>.", emoji: "🥬", unit: 4 },
        { word: "fruit", phonetic: "/fruːt/", meaning: "水果", example: "I like <em>fruit</em>.", emoji: "🍎", unit: 4 },
        { word: "parent", phonetic: "/ˈpeərənt/", meaning: "父/母", example: "My <em>parents</em> love me.", emoji: "👨‍👩‍👧", unit: 5 },
        { word: "uncle", phonetic: "/ˈʌŋkl/", meaning: "叔叔/舅舅", example: "My <em>uncle</em> is kind.", emoji: "👨", unit: 5 },
        { word: "aunt", phonetic: "/ɑːnt/", meaning: "阿姨/姑姑", example: "My <em>aunt</em> is nice.", emoji: "👩", unit: 5 },
        { word: "cousin", phonetic: "/ˈkʌzn/", meaning: "堂/表亲", example: "I play with my <em>cousin</em>.", emoji: "👦", unit: 5 },
        { word: "baby", phonetic: "/ˈbeɪbi/", meaning: "婴儿", example: "The <em>baby</em> is cute.", emoji: "👶", unit: 5 },
        { word: "doctor", phonetic: "/ˈdɒktə/", meaning: "医生", example: "The <em>doctor</em> is kind.", emoji: "👨‍⚕️", unit: 5 },
        { word: "driver", phonetic: "/ˈdraɪvə/", meaning: "司机", example: "My dad is a <em>driver</em>.", emoji: "🚗", unit: 5 },
        { word: "nurse", phonetic: "/nɜːs/", meaning: "护士", example: "The <em>nurse</em> helps me.", emoji: "👩‍⚕️", unit: 5 },
        { word: "farmer", phonetic: "/ˈfɑːmə/", meaning: "农民", example: "The <em>farmer</em> works hard.", emoji: "👨‍🌾", unit: 5 },
        { word: "cook", phonetic: "/kʊk/", meaning: "厨师/烹饪", example: "My mom can <em>cook</em>.", emoji: "👨‍🍳", unit: 5 },
    ],
    5: [ // 五年级
        { word: "old", phonetic: "/əʊld/", meaning: "年老的/旧的", example: "The house is <em>old</em>.", emoji: "🏚️", unit: 1 },
        { word: "young", phonetic: "/jʌŋ/", meaning: "年轻的", example: "She is <em>young</em>.", emoji: "👶", unit: 1 },
        { word: "funny", phonetic: "/ˈfʌni/", meaning: "有趣的", example: "He is very <em>funny</em>.", emoji: "😄", unit: 1 },
        { word: "kind", phonetic: "/kaɪnd/", meaning: "善良的", example: "She is <em>kind</em> to everyone.", emoji: "💝", unit: 1 },
        { word: "strict", phonetic: "/strɪkt/", meaning: "严格的", example: "Our teacher is <em>strict</em>.", emoji: "😠", unit: 1 },
        { word: "helpful", phonetic: "/ˈhelpfl/", meaning: "有帮助的", example: "He is very <em>helpful</em>.", emoji: "🙋", unit: 1 },
        { word: "polite", phonetic: "/pəˈlaɪt/", meaning: "有礼貌的", example: "Be <em>polite</em> to others.", emoji: "🤝", unit: 1 },
        { word: "clever", phonetic: "/ˈklevə/", meaning: "聪明的", example: "The girl is very <em>clever</em>.", emoji: "🧠", unit: 1 },
        { word: "Monday", phonetic: "/ˈmʌndeɪ/", meaning: "星期一", example: "I go to school on <em>Monday</em>.", emoji: "📅", unit: 2 },
        { word: "Tuesday", phonetic: "/ˈtjuːzdeɪ/", meaning: "星期二", example: "<em>Tuesday</em> is after Monday.", emoji: "📅", unit: 2 },
        { word: "Wednesday", phonetic: "/ˈwenzdeɪ/", meaning: "星期三", example: "We have PE on <em>Wednesday</em>.", emoji: "📅", unit: 2 },
        { word: "Thursday", phonetic: "/ˈθɜːzdeɪ/", meaning: "星期四", example: "<em>Thursday</em> is my favorite day.", emoji: "📅", unit: 2 },
        { word: "Friday", phonetic: "/ˈfraɪdeɪ/", meaning: "星期五", example: "We are happy on <em>Friday</em>.", emoji: "📅", unit: 2 },
        { word: "Saturday", phonetic: "/ˈsætədeɪ/", meaning: "星期六", example: "I play on <em>Saturday</em>.", emoji: "📅", unit: 2 },
        { word: "Sunday", phonetic: "/ˈsʌndeɪ/", meaning: "星期日", example: "<em>Sunday</em> is a rest day.", emoji: "📅", unit: 2 },
        { word: "sandwich", phonetic: "/ˈsænwɪtʃ/", meaning: "三明治", example: "I'd like a <em>sandwich</em>.", emoji: "🥪", unit: 3 },
        { word: "salad", phonetic: "/ˈsæləd/", meaning: "沙拉", example: "The <em>salad</em> is fresh.", emoji: "🥗", unit: 3 },
        { word: "hamburger", phonetic: "/ˈhæmbɜːɡə/", meaning: "汉堡包", example: "I want a <em>hamburger</em>.", emoji: "🍔", unit: 3 },
        { word: "ice cream", phonetic: "/aɪs kriːm/", meaning: "冰淇淋", example: "I love <em>ice cream</em>.", emoji: "🍦", unit: 3 },
        { word: "tea", phonetic: "/tiː/", meaning: "茶", example: "Would you like some <em>tea</em>?", emoji: "🍵", unit: 3 },
        { word: "fresh", phonetic: "/freʃ/", meaning: "新鲜的", example: "The fruit is <em>fresh</em>.", emoji: "🌿", unit: 3 },
        { word: "sweet", phonetic: "/swiːt/", meaning: "甜的", example: "The candy is <em>sweet</em>.", emoji: "🍬", unit: 3 },
        { word: "healthy", phonetic: "/ˈhelθi/", meaning: "健康的", example: "Eat <em>healthy</em> food.", emoji: "💚", unit: 3 },
        { word: "sing", phonetic: "/sɪŋ/", meaning: "唱歌", example: "I can <em>sing</em> a song.", emoji: "🎤", unit: 4 },
        { word: "dance", phonetic: "/dɑːns/", meaning: "跳舞", example: "She likes to <em>dance</em>.", emoji: "💃", unit: 4 },
        { word: "swim", phonetic: "/swɪm/", meaning: "游泳", example: "I can <em>swim</em>.", emoji: "🏊", unit: 4 },
        { word: "cook", phonetic: "/kʊk/", meaning: "烹饪", example: "She can <em>cook</em> well.", emoji: "🍳", unit: 4 },
        { word: "draw", phonetic: "/drɔː/", meaning: "画画", example: "I like to <em>draw</em>.", emoji: "🎨", unit: 4 },
        { word: "speak", phonetic: "/spiːk/", meaning: "说话", example: "Can you <em>speak</em> English?", emoji: "🗣️", unit: 4 },
        { word: "clock", phonetic: "/klɒk/", meaning: "时钟", example: "Look at the <em>clock</em>.", emoji: "🕐", unit: 5 },
        { word: "plant", phonetic: "/plɑːnt/", meaning: "植物", example: "Water the <em>plant</em>.", emoji: "🌱", unit: 5 },
        { word: "bottle", phonetic: "/ˈbɒtl/", meaning: "瓶子", example: "I have a water <em>bottle</em>.", emoji: "🍶", unit: 5 },
        { word: "photo", phonetic: "/ˈfəʊtəʊ/", meaning: "照片", example: "Take a <em>photo</em>.", emoji: "📷", unit: 5 },
        { word: "bike", phonetic: "/baɪk/", meaning: "自行车", example: "I ride a <em>bike</em>.", emoji: "🚲", unit: 5 },
        { word: "between", phonetic: "/bɪˈtwiːn/", meaning: "在…之间", example: "It is <em>between</em> the boxes.", emoji: "↔️", unit: 5 },
        { word: "above", phonetic: "/əˈbʌv/", meaning: "在…上面", example: "The bird is <em>above</em> the tree.", emoji: "⬆️", unit: 5 },
        { word: "behind", phonetic: "/bɪˈhaɪnd/", meaning: "在…后面", example: "The cat is <em>behind</em> the box.", emoji: "🔙", unit: 5 },
    ],
    6: [ // 六年级
        { word: "science", phonetic: "/ˈsaɪəns/", meaning: "科学", example: "I like <em>science</em> class.", emoji: "🔬", unit: 1 },
        { word: "museum", phonetic: "/mjuːˈziːəm/", meaning: "博物馆", example: "Let's visit the <em>museum</em>.", emoji: "🏛️", unit: 1 },
        { word: "hospital", phonetic: "/ˈhɒspɪtl/", meaning: "医院", example: "The <em>hospital</em> is big.", emoji: "🏥", unit: 1 },
        { word: "cinema", phonetic: "/ˈsɪnəmə/", meaning: "电影院", example: "Let's go to the <em>cinema</em>.", emoji: "🎬", unit: 1 },
        { word: "bookstore", phonetic: "/ˈbʊkstɔː/", meaning: "书店", example: "I go to the <em>bookstore</em>.", emoji: "📚", unit: 1 },
        { word: "crossing", phonetic: "/ˈkrɒsɪŋ/", meaning: "十字路口", example: "Turn at the <em>crossing</em>.", emoji: "🚦", unit: 1 },
        { word: "turn", phonetic: "/tɜːn/", meaning: "转弯", example: "<em>Turn</em> left at the corner.", emoji: "↩️", unit: 1 },
        { word: "straight", phonetic: "/streɪt/", meaning: "笔直地", example: "Go <em>straight</em> ahead.", emoji: "⬆️", unit: 1 },
        { word: "left", phonetic: "/left/", meaning: "左边", example: "Turn <em>left</em>.", emoji: "⬅️", unit: 1 },
        { word: "right", phonetic: "/raɪt/", meaning: "右边", example: "Turn <em>right</em>.", emoji: "➡️", unit: 1 },
        { word: "angry", phonetic: "/ˈæŋɡri/", meaning: "生气的", example: "Don't be <em>angry</em>.", emoji: "😠", unit: 2 },
        { word: "afraid", phonetic: "/əˈfreɪd/", meaning: "害怕的", example: "She is <em>afraid</em> of dogs.", emoji: "😨", unit: 2 },
        { word: "worried", phonetic: "/ˈwʌrid/", meaning: "担心的", example: "Mom looks <em>worried</em>.", emoji: "😟", unit: 2 },
        { word: "happy", phonetic: "/ˈhæpi/", meaning: "开心的", example: "I am very <em>happy</em>.", emoji: "😊", unit: 2 },
        { word: "sad", phonetic: "/sæd/", meaning: "难过的", example: "She looks <em>sad</em>.", emoji: "😢", unit: 2 },
        { word: "wear", phonetic: "/weə/", meaning: "穿/戴", example: "I <em>wear</em> a red coat.", emoji: "🧥", unit: 2 },
        { word: "deep", phonetic: "/diːp/", meaning: "深的", example: "The river is <em>deep</em>.", emoji: "🌊", unit: 2 },
        { word: "hobby", phonetic: "/ˈhɒbi/", meaning: "爱好", example: "My <em>hobby</em> is reading.", emoji: "🎯", unit: 3 },
        { word: "reading", phonetic: "/ˈriːdɪŋ/", meaning: "阅读", example: "I like <em>reading</em> books.", emoji: "📖", unit: 3 },
        { word: "hiking", phonetic: "/ˈhaɪkɪŋ/", meaning: "远足", example: "I enjoy <em>hiking</em>.", emoji: "🥾", unit: 3 },
        { word: "puzzle", phonetic: "/ˈpʌzl/", meaning: "谜/拼图", example: "I like doing <em>puzzles</em>.", emoji: "🧩", unit: 3 },
        { word: "dancing", phonetic: "/ˈdɑːnsɪŋ/", meaning: "跳舞", example: "She loves <em>dancing</em>.", emoji: "💃", unit: 3 },
        { word: "singing", phonetic: "/ˈsɪŋɪŋ/", meaning: "唱歌", example: "<em>Singing</em> makes me happy.", emoji: "🎤", unit: 3 },
        { word: "country", phonetic: "/ˈkʌntri/", meaning: "国家/乡村", example: "I love my <em>country</em>.", emoji: "🗺️", unit: 4 },
        { word: "Australia", phonetic: "/ɒˈstreɪliə/", meaning: "澳大利亚", example: "<em>Australia</em> is beautiful.", emoji: "🇦🇺", unit: 4 },
        { word: "China", phonetic: "/ˈtʃaɪnə/", meaning: "中国", example: "I live in <em>China</em>.", emoji: "🇨🇳", unit: 4 },
        { word: "America", phonetic: "/əˈmerɪkə/", meaning: "美国", example: "She is from <em>America</em>.", emoji: "🇺🇸", unit: 4 },
        { word: "teacher", phonetic: "/ˈtiːtʃə/", meaning: "老师", example: "Our <em>teacher</em> is kind.", emoji: "👨‍🏫", unit: 4 },
        { word: "student", phonetic: "/ˈstjuːdnt/", meaning: "学生", example: "I am a good <em>student</em>.", emoji: "👩‍🎓", unit: 4 },
        { word: "worker", phonetic: "/ˈwɜːkə/", meaning: "工人", example: "My dad is a <em>worker</em>.", emoji: "👷", unit: 4 },
        { word: "writer", phonetic: "/ˈraɪtə/", meaning: "作家", example: "She is a famous <em>writer</em>.", emoji: "✍️", unit: 4 },
        { word: "police", phonetic: "/pəˈliːs/", meaning: "警察", example: "The <em>police</em> help us.", emoji: "👮", unit: 4 },
        { word: "reporter", phonetic: "/rɪˈpɔːtə/", meaning: "记者", example: "He is a <em>reporter</em>.", emoji: "📰", unit: 4 },
        { word: "scientist", phonetic: "/ˈsaɪəntɪst/", meaning: "科学家", example: "I want to be a <em>scientist</em>.", emoji: "🧑‍🔬", unit: 4 },
        { word: "pilot", phonetic: "/ˈpaɪlət/", meaning: "飞行员", example: "The <em>pilot</em> flies planes.", emoji: "✈️", unit: 4 },
        { word: "coach", phonetic: "/kəʊtʃ/", meaning: "教练", example: "Our <em>coach</em> is great.", emoji: "🥇", unit: 4 },
        { word: "fisherman", phonetic: "/ˈfɪʃəmən/", meaning: "渔民", example: "The <em>fisherman</em> caught a big fish.", emoji: "🎣", unit: 4 },
    ]
};
