/**
 * 单词精灵 V3 - 人教版PEP小学英语词库
 * 按教材+上下册+单元组织，3-6年级共8册
 */
const WORD_DB = {
    "PEP_3上": {
        name: "三年级上册（人教PEP）",
        grade: 3, semester: "上",
        units: {
            1: { name: "Unit 1 Hello!", words: [
                { word: "ruler", phonetic: "/ˈruːlə/", meaning: "尺子", example: "I have a <em>ruler</em>.", emoji: "📐" },
                { word: "eraser", phonetic: "/ɪˈreɪzə/", meaning: "橡皮", example: "I need an <em>eraser</em>.", emoji: "🧽" },
                { word: "crayon", phonetic: "/ˈkreɪən/", meaning: "蜡笔", example: "I have a <em>crayon</em>.", emoji: "🖍️" },
                { word: "bag", phonetic: "/bæɡ/", meaning: "书包", example: "I have a new <em>bag</em>.", emoji: "🎒" },
                { word: "pen", phonetic: "/pen/", meaning: "钢笔", example: "This is my <em>pen</em>.", emoji: "🖊️" },
                { word: "pencil", phonetic: "/ˈpensl/", meaning: "铅笔", example: "This is my <em>pencil</em>.", emoji: "✏️" },
                { word: "pencil box", phonetic: "/ˈpensl bɒks/", meaning: "铅笔盒", example: "Where is my <em>pencil box</em>?", emoji: "📦" },
                { word: "book", phonetic: "/bʊk/", meaning: "书", example: "I read a <em>book</em>.", emoji: "📖" },
                { word: "no", phonetic: "/nəʊ/", meaning: "不", example: "<em>No</em>, thank you.", emoji: "🚫" },
            ]},
            2: { name: "Unit 2 Colors", words: [
                { word: "red", phonetic: "/red/", meaning: "红色的", example: "The apple is <em>red</em>.", emoji: "🔴" },
                { word: "green", phonetic: "/ɡriːn/", meaning: "绿色的", example: "The tree is <em>green</em>.", emoji: "🟢" },
                { word: "blue", phonetic: "/bluː/", meaning: "蓝色的", example: "The sky is <em>blue</em>.", emoji: "🔵" },
                { word: "yellow", phonetic: "/ˈjeləʊ/", meaning: "黄色的", example: "The banana is <em>yellow</em>.", emoji: "🟡" },
                { word: "black", phonetic: "/blæk/", meaning: "黑色的", example: "I have a <em>black</em> pen.", emoji: "⚫" },
                { word: "brown", phonetic: "/braʊn/", meaning: "棕色的", example: "The bear is <em>brown</em>.", emoji: "🟤" },
                { word: "white", phonetic: "/waɪt/", meaning: "白色的", example: "The snow is <em>white</em>.", emoji: "⚪" },
                { word: "orange", phonetic: "/ˈɒrɪndʒ/", meaning: "橙色的", example: "The orange is <em>orange</em>.", emoji: "🟠" },
            ]},
            3: { name: "Unit 3 Look at me!", words: [
                { word: "face", phonetic: "/feɪs/", meaning: "脸", example: "Look at my <em>face</em>.", emoji: "😊" },
                { word: "ear", phonetic: "/ɪə/", meaning: "耳朵", example: "I have two <em>ears</em>.", emoji: "👂" },
                { word: "eye", phonetic: "/aɪ/", meaning: "眼睛", example: "I have two <em>eyes</em>.", emoji: "👁️" },
                { word: "nose", phonetic: "/nəʊz/", meaning: "鼻子", example: "Touch your <em>nose</em>.", emoji: "👃" },
                { word: "mouth", phonetic: "/maʊθ/", meaning: "嘴巴", example: "Open your <em>mouth</em>.", emoji: "👄" },
                { word: "arm", phonetic: "/ɑːm/", meaning: "胳膊", example: "Wave your <em>arms</em>.", emoji: "💪" },
                { word: "hand", phonetic: "/hænd/", meaning: "手", example: "Clap your <em>hands</em>.", emoji: "✋" },
                { word: "head", phonetic: "/hed/", meaning: "头", example: "Touch your <em>head</em>.", emoji: "👤" },
                { word: "body", phonetic: "/ˈbɒdi/", meaning: "身体", example: "This is my <em>body</em>.", emoji: "🧍" },
                { word: "leg", phonetic: "/leɡ/", meaning: "腿", example: "I have two <em>legs</em>.", emoji: "🦵" },
                { word: "foot", phonetic: "/fʊt/", meaning: "脚", example: "Stamp your <em>foot</em>.", emoji: "🦶" },
            ]},
            4: { name: "Unit 4 We love animals", words: [
                { word: "cat", phonetic: "/kæt/", meaning: "猫", example: "I have a <em>cat</em>.", emoji: "🐱" },
                { word: "dog", phonetic: "/dɒɡ/", meaning: "狗", example: "The <em>dog</em> is cute.", emoji: "🐶" },
                { word: "monkey", phonetic: "/ˈmʌŋki/", meaning: "猴子", example: "The <em>monkey</em> is funny.", emoji: "🐵" },
                { word: "panda", phonetic: "/ˈpændə/", meaning: "熊猫", example: "The <em>panda</em> is fat.", emoji: "🐼" },
                { word: "duck", phonetic: "/dʌk/", meaning: "鸭子", example: "Look at the <em>duck</em>.", emoji: "🦆" },
                { word: "pig", phonetic: "/pɪɡ/", meaning: "猪", example: "The <em>pig</em> is fat.", emoji: "🐷" },
                { word: "bird", phonetic: "/bɜːd/", meaning: "鸟", example: "The <em>bird</em> can fly.", emoji: "🐦" },
                { word: "bear", phonetic: "/beə/", meaning: "熊", example: "I see a <em>bear</em>.", emoji: "🐻" },
                { word: "elephant", phonetic: "/ˈelɪfənt/", meaning: "大象", example: "The <em>elephant</em> is big.", emoji: "🐘" },
                { word: "tiger", phonetic: "/ˈtaɪɡə/", meaning: "老虎", example: "The <em>tiger</em> is strong.", emoji: "🐯" },
            ]},
            5: { name: "Unit 5 Let's eat!", words: [
                { word: "bread", phonetic: "/bred/", meaning: "面包", example: "Have some <em>bread</em>.", emoji: "🍞" },
                { word: "juice", phonetic: "/dʒuːs/", meaning: "果汁", example: "I'd like some <em>juice</em>.", emoji: "🧃" },
                { word: "egg", phonetic: "/eɡ/", meaning: "鸡蛋", example: "I eat an <em>egg</em>.", emoji: "🥚" },
                { word: "milk", phonetic: "/mɪlk/", meaning: "牛奶", example: "Drink some <em>milk</em>.", emoji: "🥛" },
                { word: "water", phonetic: "/ˈwɔːtə/", meaning: "水", example: "Can I have some <em>water</em>?", emoji: "💧" },
                { word: "cake", phonetic: "/keɪk/", meaning: "蛋糕", example: "I like <em>cake</em>.", emoji: "🎂" },
                { word: "fish", phonetic: "/fɪʃ/", meaning: "鱼", example: "I like <em>fish</em>.", emoji: "🐟" },
                { word: "rice", phonetic: "/raɪs/", meaning: "米饭", example: "Have some <em>rice</em>.", emoji: "🍚" },
            ]},
            6: { name: "Unit 6 Happy birthday!", words: [
                { word: "one", phonetic: "/wʌn/", meaning: "一", example: "I have <em>one</em> book.", emoji: "1️⃣" },
                { word: "two", phonetic: "/tuː/", meaning: "二", example: "I see <em>two</em> birds.", emoji: "2️⃣" },
                { word: "three", phonetic: "/θriː/", meaning: "三", example: "There are <em>three</em> cats.", emoji: "3️⃣" },
                { word: "four", phonetic: "/fɔː/", meaning: "四", example: "I have <em>four</em> pens.", emoji: "4️⃣" },
                { word: "five", phonetic: "/faɪv/", meaning: "五", example: "I am <em>five</em> years old.", emoji: "5️⃣" },
                { word: "six", phonetic: "/sɪks/", meaning: "六", example: "I am <em>six</em>.", emoji: "6️⃣" },
                { word: "seven", phonetic: "/ˈsevn/", meaning: "七", example: "I am <em>seven</em>.", emoji: "7️⃣" },
                { word: "eight", phonetic: "/eɪt/", meaning: "八", example: "I am <em>eight</em>.", emoji: "8️⃣" },
                { word: "nine", phonetic: "/naɪn/", meaning: "九", example: "I am <em>nine</em>.", emoji: "9️⃣" },
                { word: "ten", phonetic: "/ten/", meaning: "十", example: "I am <em>ten</em>.", emoji: "🔟" },
            ]},
        }
    },
    "PEP_3下": {
        name: "三年级下册（人教PEP）",
        grade: 3, semester: "下",
        units: {
            1: { name: "Unit 1 Welcome back to school!", words: [
                { word: "boy", phonetic: "/bɔɪ/", meaning: "男孩", example: "I am a <em>boy</em>.", emoji: "👦" },
                { word: "girl", phonetic: "/ɡɜːl/", meaning: "女孩", example: "She is a <em>girl</em>.", emoji: "👧" },
                { word: "teacher", phonetic: "/ˈtiːtʃə/", meaning: "老师", example: "Our <em>teacher</em> is kind.", emoji: "👨‍🏫" },
                { word: "student", phonetic: "/ˈstjuːdnt/", meaning: "学生", example: "I am a good <em>student</em>.", emoji: "👩‍🎓" },
                { word: "new", phonetic: "/njuː/", meaning: "新的", example: "I have a <em>new</em> friend.", emoji: "✨" },
                { word: "friend", phonetic: "/frend/", meaning: "朋友", example: "She is my <em>friend</em>.", emoji: "🤝" },
                { word: "today", phonetic: "/təˈdeɪ/", meaning: "今天", example: "<em>Today</em> is a good day.", emoji: "📅" },
                { word: "China", phonetic: "/ˈtʃaɪnə/", meaning: "中国", example: "I live in <em>China</em>.", emoji: "🇨🇳" },
            ]},
            2: { name: "Unit 2 My family", words: [
                { word: "father", phonetic: "/ˈfɑːðə/", meaning: "父亲", example: "My <em>father</em> is tall.", emoji: "👨" },
                { word: "mother", phonetic: "/ˈmʌðə/", meaning: "母亲", example: "My <em>mother</em> is kind.", emoji: "👩" },
                { word: "grandfather", phonetic: "/ˈɡrɑːndˌfɑːðə/", meaning: "祖父", example: "My <em>grandfather</em> is old.", emoji: "👴" },
                { word: "grandmother", phonetic: "/ˈɡrɑːndˌmʌðə/", meaning: "祖母", example: "My <em>grandmother</em> is nice.", emoji: "👵" },
                { word: "brother", phonetic: "/ˈbrʌðə/", meaning: "兄弟", example: "My <em>brother</em> is five.", emoji: "👦" },
                { word: "sister", phonetic: "/ˈsɪstə/", meaning: "姐妹", example: "My <em>sister</em> is cute.", emoji: "👧" },
                { word: "family", phonetic: "/ˈfæmɪli/", meaning: "家庭", example: "I love my <em>family</em>.", emoji: "👨‍👩‍👧" },
            ]},
            3: { name: "Unit 3 At the zoo", words: [
                { word: "thin", phonetic: "/θɪn/", meaning: "瘦的", example: "The monkey is <em>thin</em>.", emoji: "🐒" },
                { word: "fat", phonetic: "/fæt/", meaning: "胖的", example: "The panda is <em>fat</em>.", emoji: "🐼" },
                { word: "tall", phonetic: "/tɔːl/", meaning: "高的", example: "The giraffe is <em>tall</em>.", emoji: "🦒" },
                { word: "short", phonetic: "/ʃɔːt/", meaning: "矮的/短的", example: "The dog is <em>short</em>.", emoji: "🐕" },
                { word: "long", phonetic: "/lɒŋ/", meaning: "长的", example: "The snake is <em>long</em>.", emoji: "🐍" },
                { word: "small", phonetic: "/smɔːl/", meaning: "小的", example: "The bird is <em>small</em>.", emoji: "🐦" },
                { word: "big", phonetic: "/bɪɡ/", meaning: "大的", example: "The elephant is <em>big</em>.", emoji: "🐘" },
                { word: "giraffe", phonetic: "/dʒɪˈrɑːf/", meaning: "长颈鹿", example: "The <em>giraffe</em> is so tall.", emoji: "🦒" },
                { word: "tail", phonetic: "/teɪl/", meaning: "尾巴", example: "The monkey has a long <em>tail</em>.", emoji: "🐒" },
            ]},
            4: { name: "Unit 4 Where is my car?", words: [
                { word: "on", phonetic: "/ɒn/", meaning: "在…上面", example: "The book is <em>on</em> the desk.", emoji: "⬆️" },
                { word: "in", phonetic: "/ɪn/", meaning: "在…里面", example: "The cat is <em>in</em> the box.", emoji: "📦" },
                { word: "under", phonetic: "/ˈʌndə/", meaning: "在…下面", example: "The ball is <em>under</em> the chair.", emoji: "⬇️" },
                { word: "chair", phonetic: "/tʃeə/", meaning: "椅子", example: "Sit on the <em>chair</em>.", emoji: "🪑" },
                { word: "desk", phonetic: "/desk/", meaning: "课桌", example: "The <em>desk</em> is new.", emoji: "📚" },
                { word: "cap", phonetic: "/kæp/", meaning: "帽子", example: "Put on your <em>cap</em>.", emoji: "🧢" },
                { word: "ball", phonetic: "/bɔːl/", meaning: "球", example: "I have a <em>ball</em>.", emoji: "⚽" },
                { word: "car", phonetic: "/kɑː/", meaning: "小汽车", example: "I have a toy <em>car</em>.", emoji: "🚗" },
                { word: "boat", phonetic: "/bəʊt/", meaning: "小船", example: "Row the <em>boat</em>.", emoji: "🚣" },
                { word: "map", phonetic: "/mæp/", meaning: "地图", example: "Look at the <em>map</em>.", emoji: "🗺️" },
            ]},
            5: { name: "Unit 5 Do you like pears?", words: [
                { word: "pear", phonetic: "/peə/", meaning: "梨", example: "I like <em>pears</em>.", emoji: "🍐" },
                { word: "apple", phonetic: "/ˈæpl/", meaning: "苹果", example: "I like <em>apples</em>.", emoji: "🍎" },
                { word: "orange", phonetic: "/ˈɒrɪndʒ/", meaning: "橙子", example: "Have an <em>orange</em>.", emoji: "🍊" },
                { word: "banana", phonetic: "/bəˈnɑːnə/", meaning: "香蕉", example: "I like <em>bananas</em>.", emoji: "🍌" },
                { word: "watermelon", phonetic: "/ˈwɔːtəmelən/", meaning: "西瓜", example: "The <em>watermelon</em> is big.", emoji: "🍉" },
                { word: "strawberry", phonetic: "/ˈstrɔːbəri/", meaning: "草莓", example: "I like <em>strawberries</em>.", emoji: "🍓" },
                { word: "grape", phonetic: "/ɡreɪp/", meaning: "葡萄", example: "Have some <em>grapes</em>.", emoji: "🍇" },
                { word: "fruit", phonetic: "/fruːt/", meaning: "水果", example: "I like <em>fruit</em>.", emoji: "🍎" },
            ]},
            6: { name: "Unit 6 How many?", words: [
                { word: "eleven", phonetic: "/ɪˈlevn/", meaning: "十一", example: "I see <em>eleven</em> birds.", emoji: "🔢" },
                { word: "twelve", phonetic: "/twelv/", meaning: "十二", example: "There are <em>twelve</em> months.", emoji: "🔢" },
                { word: "thirteen", phonetic: "/ˌθɜːˈtiːn/", meaning: "十三", example: "I have <em>thirteen</em> pens.", emoji: "🔢" },
                { word: "fourteen", phonetic: "/ˌfɔːˈtiːn/", meaning: "十四", example: "I am <em>fourteen</em>.", emoji: "🔢" },
                { word: "fifteen", phonetic: "/ˌfɪfˈtiːn/", meaning: "十五", example: "I have <em>fifteen</em> books.", emoji: "🔢" },
                { word: "sixteen", phonetic: "/ˌsɪkˈstiːn/", meaning: "十六", example: "I see <em>sixteen</em> cats.", emoji: "🔢" },
                { word: "seventeen", phonetic: "/ˌsevnˈtiːn/", meaning: "十七", example: "There are <em>seventeen</em>.", emoji: "🔢" },
                { word: "eighteen", phonetic: "/ˌeɪˈtiːn/", meaning: "十八", example: "I have <em>eighteen</em>.", emoji: "🔢" },
                { word: "nineteen", phonetic: "/ˌnaɪnˈtiːn/", meaning: "十九", example: "I count <em>nineteen</em>.", emoji: "🔢" },
                { word: "twenty", phonetic: "/ˈtwenti/", meaning: "二十", example: "I have <em>twenty</em> friends.", emoji: "🔢" },
                { word: "kite", phonetic: "/kaɪt/", meaning: "风筝", example: "Let's fly a <em>kite</em>.", emoji: "🪁" },
            ]},
        }
    },
    "PEP_4上": {
        name: "四年级上册（人教PEP）",
        grade: 4, semester: "上",
        units: {
            1: { name: "Unit 1 My classroom", words: [
                { word: "classroom", phonetic: "/ˈklɑːsruːm/", meaning: "教室", example: "This is our <em>classroom</em>.", emoji: "🏫" },
                { word: "window", phonetic: "/ˈwɪndəʊ/", meaning: "窗户", example: "Open the <em>window</em>.", emoji: "🪟" },
                { word: "blackboard", phonetic: "/ˈblækbɔːd/", meaning: "黑板", example: "Look at the <em>blackboard</em>.", emoji: "⬛" },
                { word: "light", phonetic: "/laɪt/", meaning: "灯", example: "Turn on the <em>light</em>.", emoji: "💡" },
                { word: "picture", phonetic: "/ˈpɪktʃə/", meaning: "图画", example: "This is a <em>picture</em>.", emoji: "🖼️" },
                { word: "door", phonetic: "/dɔː/", meaning: "门", example: "Close the <em>door</em>.", emoji: "🚪" },
                { word: "floor", phonetic: "/flɔː/", meaning: "地板", example: "The <em>floor</em> is clean.", emoji: "🏠" },
                { word: "computer", phonetic: "/kəmˈpjuːtə/", meaning: "电脑", example: "I use the <em>computer</em>.", emoji: "💻" },
                { word: "wall", phonetic: "/wɔːl/", meaning: "墙壁", example: "The <em>wall</em> is white.", emoji: "🧱" },
                { word: "fan", phonetic: "/fæn/", meaning: "风扇", example: "The <em>fan</em> is on.", emoji: "🪭" },
                { word: "clean", phonetic: "/kliːn/", meaning: "打扫/干净的", example: "Let me <em>clean</em> the board.", emoji: "🧹" },
            ]},
            2: { name: "Unit 2 My schoolbag", words: [
                { word: "schoolbag", phonetic: "/ˈskuːlbæɡ/", meaning: "书包", example: "I have a new <em>schoolbag</em>.", emoji: "🎒" },
                { word: "maths book", phonetic: "/mæθs bʊk/", meaning: "数学书", example: "Where is my <em>maths book</em>?", emoji: "📐" },
                { word: "English book", phonetic: "/ˈɪŋɡlɪʃ bʊk/", meaning: "英语书", example: "I like my <em>English book</em>.", emoji: "📖" },
                { word: "Chinese book", phonetic: "/tʃaɪˈniːz bʊk/", meaning: "语文书", example: "Open your <em>Chinese book</em>.", emoji: "📕" },
                { word: "storybook", phonetic: "/ˈstɔːribʊk/", meaning: "故事书", example: "I read a <em>storybook</em>.", emoji: "📚" },
                { word: "candy", phonetic: "/ˈkændi/", meaning: "糖果", example: "I have some <em>candy</em>.", emoji: "🍬" },
                { word: "notebook", phonetic: "/ˈnəʊtbʊk/", meaning: "笔记本", example: "Write in your <em>notebook</em>.", emoji: "📓" },
                { word: "toy", phonetic: "/tɔɪ/", meaning: "玩具", example: "I have a <em>toy</em>.", emoji: "🧸" },
                { word: "key", phonetic: "/kiː/", meaning: "钥匙", example: "I lost my <em>key</em>.", emoji: "🔑" },
            ]},
            3: { name: "Unit 3 My friends", words: [
                { word: "strong", phonetic: "/strɒŋ/", meaning: "强壮的", example: "My dad is <em>strong</em>.", emoji: "💪" },
                { word: "quiet", phonetic: "/ˈkwaɪət/", meaning: "安静的", example: "Please be <em>quiet</em>.", emoji: "🤫" },
                { word: "friendly", phonetic: "/ˈfrendli/", meaning: "友好的", example: "She is very <em>friendly</em>.", emoji: "🤝" },
                { word: "hair", phonetic: "/heə/", meaning: "头发", example: "She has long <em>hair</em>.", emoji: "💇" },
                { word: "shoe", phonetic: "/ʃuː/", meaning: "鞋子", example: "My <em>shoes</em> are new.", emoji: "👟" },
                { word: "glasses", phonetic: "/ˈɡlɑːsɪz/", meaning: "眼镜", example: "He wears <em>glasses</em>.", emoji: "👓" },
                { word: "his", phonetic: "/hɪz/", meaning: "他的", example: "<em>His</em> bag is blue.", emoji: "👦" },
                { word: "her", phonetic: "/hɜː/", meaning: "她的", example: "<em>Her</em> name is Lily.", emoji: "👧" },
                { word: "right", phonetic: "/raɪt/", meaning: "正确的/右边", example: "You are <em>right</em>.", emoji: "✅" },
            ]},
            4: { name: "Unit 4 My home", words: [
                { word: "bedroom", phonetic: "/ˈbedruːm/", meaning: "卧室", example: "This is my <em>bedroom</em>.", emoji: "🛏️" },
                { word: "living room", phonetic: "/ˈlɪvɪŋ ruːm/", meaning: "客厅", example: "This is the <em>living room</em>.", emoji: "🛋️" },
                { word: "study", phonetic: "/ˈstʌdi/", meaning: "书房", example: "I read in the <em>study</em>.", emoji: "📖" },
                { word: "kitchen", phonetic: "/ˈkɪtʃɪn/", meaning: "厨房", example: "Mom is in the <em>kitchen</em>.", emoji: "🍳" },
                { word: "bathroom", phonetic: "/ˈbɑːθruːm/", meaning: "浴室", example: "Go to the <em>bathroom</em>.", emoji: "🚿" },
                { word: "phone", phonetic: "/fəʊn/", meaning: "电话", example: "Answer the <em>phone</em>.", emoji: "📱" },
                { word: "sofa", phonetic: "/ˈsəʊfə/", meaning: "沙发", example: "Sit on the <em>sofa</em>.", emoji: "🛋️" },
                { word: "fridge", phonetic: "/frɪdʒ/", meaning: "冰箱", example: "The food is in the <em>fridge</em>.", emoji: "🧊" },
                { word: "table", phonetic: "/ˈteɪbl/", meaning: "桌子", example: "The <em>table</em> is big.", emoji: "🪑" },
            ]},
            5: { name: "Unit 5 Dinner's ready", words: [
                { word: "beef", phonetic: "/biːf/", meaning: "牛肉", example: "I like <em>beef</em>.", emoji: "🥩" },
                { word: "chicken", phonetic: "/ˈtʃɪkɪn/", meaning: "鸡肉", example: "Have some <em>chicken</em>.", emoji: "🍗" },
                { word: "noodle", phonetic: "/ˈnuːdl/", meaning: "面条", example: "I'd like some <em>noodles</em>.", emoji: "🍜" },
                { word: "soup", phonetic: "/suːp/", meaning: "汤", example: "The <em>soup</em> is hot.", emoji: "🍲" },
                { word: "vegetable", phonetic: "/ˈvedʒtəbl/", meaning: "蔬菜", example: "Eat your <em>vegetables</em>.", emoji: "🥬" },
                { word: "chopsticks", phonetic: "/ˈtʃɒpstɪks/", meaning: "筷子", example: "Use <em>chopsticks</em>.", emoji: "🥢" },
                { word: "bowl", phonetic: "/bəʊl/", meaning: "碗", example: "I have a <em>bowl</em>.", emoji: "🥣" },
                { word: "fork", phonetic: "/fɔːk/", meaning: "叉子", example: "Use a <em>fork</em>.", emoji: "🍴" },
                { word: "knife", phonetic: "/naɪf/", meaning: "刀", example: "Use a <em>knife</em>.", emoji: "🔪" },
                { word: "spoon", phonetic: "/spuːn/", meaning: "勺子", example: "Use a <em>spoon</em>.", emoji: "🥄" },
                { word: "dinner", phonetic: "/ˈdɪnə/", meaning: "晚餐", example: "<em>Dinner</em> is ready.", emoji: "🍽️" },
            ]},
            6: { name: "Unit 6 Meet my family", words: [
                { word: "parents", phonetic: "/ˈpeərənts/", meaning: "父母", example: "My <em>parents</em> love me.", emoji: "👨‍👩‍👧" },
                { word: "uncle", phonetic: "/ˈʌŋkl/", meaning: "叔叔/舅舅", example: "My <em>uncle</em> is kind.", emoji: "👨" },
                { word: "aunt", phonetic: "/ɑːnt/", meaning: "阿姨/姑姑", example: "My <em>aunt</em> is nice.", emoji: "👩" },
                { word: "cousin", phonetic: "/ˈkʌzn/", meaning: "堂/表亲", example: "I play with my <em>cousin</em>.", emoji: "👦" },
                { word: "baby", phonetic: "/ˈbeɪbi/", meaning: "婴儿", example: "The <em>baby</em> is cute.", emoji: "👶" },
                { word: "doctor", phonetic: "/ˈdɒktə/", meaning: "医生", example: "The <em>doctor</em> is kind.", emoji: "👨‍⚕️" },
                { word: "driver", phonetic: "/ˈdraɪvə/", meaning: "司机", example: "My dad is a <em>driver</em>.", emoji: "🚗" },
                { word: "farmer", phonetic: "/ˈfɑːmə/", meaning: "农民", example: "The <em>farmer</em> works hard.", emoji: "👨‍🌾" },
                { word: "nurse", phonetic: "/nɜːs/", meaning: "护士", example: "The <em>nurse</em> helps me.", emoji: "👩‍⚕️" },
                { word: "cook", phonetic: "/kʊk/", meaning: "厨师", example: "My mom can <em>cook</em>.", emoji: "👨‍🍳" },
                { word: "people", phonetic: "/ˈpiːpl/", meaning: "人们", example: "There are many <em>people</em>.", emoji: "👥" },
            ]},
        }
    },
    "PEP_4下": {
        name: "四年级下册（人教PEP）",
        grade: 4, semester: "下",
        units: {
            1: { name: "Unit 1 My school", words: [
                { word: "library", phonetic: "/ˈlaɪbrəri/", meaning: "图书馆", example: "The <em>library</em> is big.", emoji: "📚" },
                { word: "playground", phonetic: "/ˈpleɪɡraʊnd/", meaning: "操场", example: "Let's go to the <em>playground</em>.", emoji: "🏟️" },
                { word: "garden", phonetic: "/ˈɡɑːdn/", meaning: "花园", example: "The <em>garden</em> is beautiful.", emoji: "🌷" },
                { word: "art room", phonetic: "/ɑːt ruːm/", meaning: "美术教室", example: "We draw in the <em>art room</em>.", emoji: "🎨" },
                { word: "music room", phonetic: "/ˈmjuːzɪk ruːm/", meaning: "音乐教室", example: "We sing in the <em>music room</em>.", emoji: "🎵" },
                { word: "computer room", phonetic: "/kəmˈpjuːtə ruːm/", meaning: "电脑室", example: "I like the <em>computer room</em>.", emoji: "💻" },
                { word: "gym", phonetic: "/dʒɪm/", meaning: "体育馆", example: "We play in the <em>gym</em>.", emoji: "🏋️" },
                { word: "first", phonetic: "/fɜːst/", meaning: "第一的", example: "It's on the <em>first</em> floor.", emoji: "1️⃣" },
                { word: "second", phonetic: "/ˈsekənd/", meaning: "第二的", example: "It's on the <em>second</em> floor.", emoji: "2️⃣" },
            ]},
            2: { name: "Unit 2 What time is it?", words: [
                { word: "breakfast", phonetic: "/ˈbrekfəst/", meaning: "早餐", example: "I have <em>breakfast</em> at seven.", emoji: "🥣" },
                { word: "lunch", phonetic: "/lʌntʃ/", meaning: "午餐", example: "<em>Lunch</em> is at twelve.", emoji: "🍱" },
                { word: "dinner", phonetic: "/ˈdɪnə/", meaning: "正餐", example: "I have <em>dinner</em> at six.", emoji: "🍽️" },
                { word: "o'clock", phonetic: "/əˈklɒk/", meaning: "…点钟", example: "It's eight <em>o'clock</em>.", emoji: "🕐" },
                { word: "get up", phonetic: "/ɡet ʌp/", meaning: "起床", example: "I <em>get up</em> at six.", emoji: "⏰" },
                { word: "go to school", phonetic: "/ɡəʊ tuː skuːl/", meaning: "上学", example: "I <em>go to school</em> at seven.", emoji: "🏫" },
                { word: "go home", phonetic: "/ɡəʊ həʊm/", meaning: "回家", example: "I <em>go home</em> at four.", emoji: "🏠" },
                { word: "hurry up", phonetic: "/ˈhʌri ʌp/", meaning: "快点", example: "<em>Hurry up</em>! We're late.", emoji: "🏃" },
                { word: "English class", phonetic: "/ˈɪŋɡlɪʃ klɑːs/", meaning: "英语课", example: "I have <em>English class</em> today.", emoji: "📖" },
                { word: "music class", phonetic: "/ˈmjuːzɪk klɑːs/", meaning: "音乐课", example: "I like <em>music class</em>.", emoji: "🎵" },
                { word: "PE class", phonetic: "/piː iː klɑːs/", meaning: "体育课", example: "We run in <em>PE class</em>.", emoji: "⚽" },
            ]},
            3: { name: "Unit 3 Weather", words: [
                { word: "cold", phonetic: "/kəʊld/", meaning: "寒冷的", example: "It's <em>cold</em> in winter.", emoji: "🥶" },
                { word: "cool", phonetic: "/kuːl/", meaning: "凉爽的", example: "It's <em>cool</em> in autumn.", emoji: "🍂" },
                { word: "warm", phonetic: "/wɔːm/", meaning: "温暖的", example: "It's <em>warm</em> in spring.", emoji: "🌸" },
                { word: "hot", phonetic: "/hɒt/", meaning: "炎热的", example: "It's <em>hot</em> in summer.", emoji: "🥵" },
                { word: "sunny", phonetic: "/ˈsʌni/", meaning: "晴朗的", example: "It's <em>sunny</em> today.", emoji: "☀️" },
                { word: "windy", phonetic: "/ˈwɪndi/", meaning: "有风的", example: "It's <em>windy</em> today.", emoji: "💨" },
                { word: "cloudy", phonetic: "/ˈklaʊdi/", meaning: "多云的", example: "It's <em>cloudy</em> today.", emoji: "☁️" },
                { word: "snowy", phonetic: "/ˈsnəʊi/", meaning: "下雪的", example: "It's <em>snowy</em> today.", emoji: "❄️" },
                { word: "rainy", phonetic: "/ˈreɪni/", meaning: "下雨的", example: "It's <em>rainy</em> today.", emoji: "🌧️" },
                { word: "weather", phonetic: "/ˈweðə/", meaning: "天气", example: "How is the <em>weather</em>?", emoji: "🌤️" },
                { word: "outside", phonetic: "/ˌaʊtˈsaɪd/", meaning: "外面", example: "Let's play <em>outside</em>.", emoji: "🌳" },
            ]},
            4: { name: "Unit 4 At the farm", words: [
                { word: "tomato", phonetic: "/təˈmɑːtəʊ/", meaning: "西红柿", example: "I like <em>tomatoes</em>.", emoji: "🍅" },
                { word: "potato", phonetic: "/pəˈteɪtəʊ/", meaning: "土豆", example: "I like <em>potatoes</em>.", emoji: "🥔" },
                { word: "carrot", phonetic: "/ˈkærət/", meaning: "胡萝卜", example: "Rabbits like <em>carrots</em>.", emoji: "🥕" },
                { word: "horse", phonetic: "/hɔːs/", meaning: "马", example: "The <em>horse</em> is fast.", emoji: "🐴" },
                { word: "cow", phonetic: "/kaʊ/", meaning: "奶牛", example: "The <em>cow</em> is big.", emoji: "🐄" },
                { word: "sheep", phonetic: "/ʃiːp/", meaning: "绵羊", example: "The <em>sheep</em> is white.", emoji: "🐑" },
                { word: "hen", phonetic: "/hen/", meaning: "母鸡", example: "The <em>hen</em> has chicks.", emoji: "🐔" },
                { word: "lamb", phonetic: "/læm/", meaning: "小羊", example: "The <em>lamb</em> is cute.", emoji: "🐑" },
                { word: "goat", phonetic: "/ɡəʊt/", meaning: "山羊", example: "The <em>goat</em> is on the hill.", emoji: "🐐" },
                { word: "animal", phonetic: "/ˈænɪml/", meaning: "动物", example: "I love <em>animals</em>.", emoji: "🐾" },
                { word: "these", phonetic: "/ðiːz/", meaning: "这些", example: "<em>These</em> are carrots.", emoji: "👉" },
            ]},
            5: { name: "Unit 5 My clothes", words: [
                { word: "clothes", phonetic: "/kləʊðz/", meaning: "衣服", example: "I like my new <em>clothes</em>.", emoji: "👕" },
                { word: "pants", phonetic: "/pænts/", meaning: "裤子", example: "I wear <em>pants</em>.", emoji: "👖" },
                { word: "hat", phonetic: "/hæt/", meaning: "帽子", example: "Put on your <em>hat</em>.", emoji: "🎩" },
                { word: "dress", phonetic: "/dres/", meaning: "连衣裙", example: "She wears a <em>dress</em>.", emoji: "👗" },
                { word: "skirt", phonetic: "/skɜːt/", meaning: "短裙", example: "The <em>skirt</em> is pretty.", emoji: "👗" },
                { word: "coat", phonetic: "/kəʊt/", meaning: "外套", example: "Put on your <em>coat</em>.", emoji: "🧥" },
                { word: "sweater", phonetic: "/ˈswetə/", meaning: "毛衣", example: "I wear a <em>sweater</em>.", emoji: "🧶" },
                { word: "shirt", phonetic: "/ʃɜːt/", meaning: "衬衫", example: "He wears a <em>shirt</em>.", emoji: "👔" },
                { word: "jacket", phonetic: "/ˈdʒækɪt/", meaning: "夹克", example: "This <em>jacket</em> is cool.", emoji: "🧥" },
                { word: "shorts", phonetic: "/ʃɔːts/", meaning: "短裤", example: "I wear <em>shorts</em> in summer.", emoji: "🩳" },
            ]},
            6: { name: "Unit 6 Shopping", words: [
                { word: "gloves", phonetic: "/ɡlʌvz/", meaning: "手套", example: "I wear <em>gloves</em> in winter.", emoji: "🧤" },
                { word: "scarf", phonetic: "/skɑːf/", meaning: "围巾", example: "Put on your <em>scarf</em>.", emoji: "🧣" },
                { word: "umbrella", phonetic: "/ʌmˈbrelə/", meaning: "雨伞", example: "Take an <em>umbrella</em>.", emoji: "☂️" },
                { word: "sunglasses", phonetic: "/ˈsʌnɡlɑːsɪz/", meaning: "太阳镜", example: "I wear <em>sunglasses</em>.", emoji: "🕶️" },
                { word: "pretty", phonetic: "/ˈprɪti/", meaning: "漂亮的", example: "The dress is <em>pretty</em>.", emoji: "✨" },
                { word: "expensive", phonetic: "/ɪkˈspensɪv/", meaning: "昂贵的", example: "This bag is <em>expensive</em>.", emoji: "💰" },
                { word: "cheap", phonetic: "/tʃiːp/", meaning: "便宜的", example: "This hat is <em>cheap</em>.", emoji: "💵" },
                { word: "nice", phonetic: "/naɪs/", meaning: "好的", example: "This is <em>nice</em>.", emoji: "👍" },
                { word: "try on", phonetic: "/traɪ ɒn/", meaning: "试穿", example: "Can I <em>try on</em> this shirt?", emoji: "🪞" },
                { word: "size", phonetic: "/saɪz/", meaning: "尺码", example: "What <em>size</em> do you need?", emoji: "📏" },
            ]},
        }
    },
    "PEP_5上": {
        name: "五年级上册（人教PEP）",
        grade: 5, semester: "上",
        units: {
            1: { name: "Unit 1 What's he like?", words: [
                { word: "old", phonetic: "/əʊld/", meaning: "年老的/旧的", example: "The house is <em>old</em>.", emoji: "🏚️" },
                { word: "young", phonetic: "/jʌŋ/", meaning: "年轻的", example: "She is <em>young</em>.", emoji: "👶" },
                { word: "funny", phonetic: "/ˈfʌni/", meaning: "有趣的", example: "He is very <em>funny</em>.", emoji: "😄" },
                { word: "kind", phonetic: "/kaɪnd/", meaning: "善良的", example: "She is <em>kind</em> to everyone.", emoji: "💝" },
                { word: "strict", phonetic: "/strɪkt/", meaning: "严格的", example: "Our teacher is <em>strict</em>.", emoji: "😠" },
                { word: "polite", phonetic: "/pəˈlaɪt/", meaning: "有礼貌的", example: "Be <em>polite</em> to others.", emoji: "🤝" },
                { word: "helpful", phonetic: "/ˈhelpfl/", meaning: "有帮助的", example: "He is very <em>helpful</em>.", emoji: "🙋" },
                { word: "clever", phonetic: "/ˈklevə/", meaning: "聪明的", example: "The girl is very <em>clever</em>.", emoji: "🧠" },
                { word: "shy", phonetic: "/ʃaɪ/", meaning: "害羞的", example: "She is <em>shy</em>.", emoji: "😊" },
                { word: "hard-working", phonetic: "/hɑːd ˈwɜːkɪŋ/", meaning: "勤奋的", example: "He is <em>hard-working</em>.", emoji: "📚" },
            ]},
            2: { name: "Unit 2 My week", words: [
                { word: "Monday", phonetic: "/ˈmʌndeɪ/", meaning: "星期一", example: "I go to school on <em>Monday</em>.", emoji: "📅" },
                { word: "Tuesday", phonetic: "/ˈtjuːzdeɪ/", meaning: "星期二", example: "<em>Tuesday</em> is after Monday.", emoji: "📅" },
                { word: "Wednesday", phonetic: "/ˈwenzdeɪ/", meaning: "星期三", example: "We have PE on <em>Wednesday</em>.", emoji: "📅" },
                { word: "Thursday", phonetic: "/ˈθɜːzdeɪ/", meaning: "星期四", example: "<em>Thursday</em> is my favorite day.", emoji: "📅" },
                { word: "Friday", phonetic: "/ˈfraɪdeɪ/", meaning: "星期五", example: "We are happy on <em>Friday</em>.", emoji: "📅" },
                { word: "Saturday", phonetic: "/ˈsætədeɪ/", meaning: "星期六", example: "I play on <em>Saturday</em>.", emoji: "📅" },
                { word: "Sunday", phonetic: "/ˈsʌndeɪ/", meaning: "星期日", example: "<em>Sunday</em> is a rest day.", emoji: "📅" },
                { word: "weekend", phonetic: "/ˌwiːkˈend/", meaning: "周末", example: "I play on the <em>weekend</em>.", emoji: "🎮" },
                { word: "wash", phonetic: "/wɒʃ/", meaning: "洗", example: "I <em>wash</em> my clothes.", emoji: "🧺" },
                { word: "watch", phonetic: "/wɒtʃ/", meaning: "看/观看", example: "I <em>watch</em> TV.", emoji: "📺" },
                { word: "homework", phonetic: "/ˈhəʊmwɜːk/", meaning: "家庭作业", example: "I do my <em>homework</em>.", emoji: "📝" },
            ]},
            3: { name: "Unit 3 What would you like?", words: [
                { word: "sandwich", phonetic: "/ˈsænwɪtʃ/", meaning: "三明治", example: "I'd like a <em>sandwich</em>.", emoji: "🥪" },
                { word: "salad", phonetic: "/ˈsæləd/", meaning: "沙拉", example: "The <em>salad</em> is fresh.", emoji: "🥗" },
                { word: "hamburger", phonetic: "/ˈhæmbɜːɡə/", meaning: "汉堡包", example: "I want a <em>hamburger</em>.", emoji: "🍔" },
                { word: "ice cream", phonetic: "/aɪs kriːm/", meaning: "冰淇淋", example: "I love <em>ice cream</em>.", emoji: "🍦" },
                { word: "tea", phonetic: "/tiː/", meaning: "茶", example: "Would you like some <em>tea</em>?", emoji: "🍵" },
                { word: "fresh", phonetic: "/freʃ/", meaning: "新鲜的", example: "The fruit is <em>fresh</em>.", emoji: "🌿" },
                { word: "sweet", phonetic: "/swiːt/", meaning: "甜的", example: "The candy is <em>sweet</em>.", emoji: "🍬" },
                { word: "healthy", phonetic: "/ˈhelθi/", meaning: "健康的", example: "Eat <em>healthy</em> food.", emoji: "💚" },
                { word: "delicious", phonetic: "/dɪˈlɪʃəs/", meaning: "美味的", example: "The food is <em>delicious</em>.", emoji: "😋" },
                { word: "favourite", phonetic: "/ˈfeɪvərɪt/", meaning: "最喜欢的", example: "What's your <em>favourite</em> food?", emoji: "⭐" },
                { word: "thirsty", phonetic: "/ˈθɜːsti/", meaning: "渴的", example: "I am <em>thirsty</em>.", emoji: "🥤" },
                { word: "hungry", phonetic: "/ˈhʌŋɡri/", meaning: "饿的", example: "I am <em>hungry</em>.", emoji: "🤤" },
            ]},
            4: { name: "Unit 4 What can you do?", words: [
                { word: "sing", phonetic: "/sɪŋ/", meaning: "唱歌", example: "I can <em>sing</em> a song.", emoji: "🎤" },
                { word: "dance", phonetic: "/dɑːns/", meaning: "跳舞", example: "She likes to <em>dance</em>.", emoji: "💃" },
                { word: "swim", phonetic: "/swɪm/", meaning: "游泳", example: "I can <em>swim</em>.", emoji: "🏊" },
                { word: "draw", phonetic: "/drɔː/", meaning: "画画", example: "I like to <em>draw</em>.", emoji: "🎨" },
                { word: "cook", phonetic: "/kʊk/", meaning: "烹饪", example: "She can <em>cook</em> well.", emoji: "🍳" },
                { word: "speak", phonetic: "/spiːk/", meaning: "说话", example: "Can you <em>speak</em> English?", emoji: "🗣️" },
                { word: "play basketball", phonetic: "/pleɪ ˈbɑːskɪtbɔːl/", meaning: "打篮球", example: "I can <em>play basketball</em>.", emoji: "🏀" },
                { word: "play ping-pong", phonetic: "/pleɪ pɪŋ pɒŋ/", meaning: "打乒乓球", example: "Let's <em>play ping-pong</em>.", emoji: "🏓" },
                { word: "kung fu", phonetic: "/kʌŋ fuː/", meaning: "功夫", example: "I can do <em>kung fu</em>.", emoji: "🥋" },
                { word: "wonderful", phonetic: "/ˈwʌndəfl/", meaning: "精彩的", example: "That's <em>wonderful</em>!", emoji: "🌟" },
            ]},
            5: { name: "Unit 5 There is a big bed", words: [
                { word: "clock", phonetic: "/klɒk/", meaning: "时钟", example: "Look at the <em>clock</em>.", emoji: "🕐" },
                { word: "plant", phonetic: "/plɑːnt/", meaning: "植物", example: "Water the <em>plant</em>.", emoji: "🌱" },
                { word: "bottle", phonetic: "/ˈbɒtl/", meaning: "瓶子", example: "I have a water <em>bottle</em>.", emoji: "🍶" },
                { word: "photo", phonetic: "/ˈfəʊtəʊ/", meaning: "照片", example: "Take a <em>photo</em>.", emoji: "📷" },
                { word: "bike", phonetic: "/baɪk/", meaning: "自行车", example: "I ride a <em>bike</em>.", emoji: "🚲" },
                { word: "front", phonetic: "/frʌnt/", meaning: "前面", example: "It's in <em>front</em> of the box.", emoji: "⬆️" },
                { word: "between", phonetic: "/bɪˈtwiːn/", meaning: "在…之间", example: "It is <em>between</em> the boxes.", emoji: "↔️" },
                { word: "above", phonetic: "/əˈbʌv/", meaning: "在…上面", example: "The bird is <em>above</em> the tree.", emoji: "⬆️" },
                { word: "beside", phonetic: "/bɪˈsaɪd/", meaning: "在…旁边", example: "The cat is <em>beside</em> me.", emoji: "👉" },
                { word: "behind", phonetic: "/bɪˈhaɪnd/", meaning: "在…后面", example: "The cat is <em>behind</em> the box.", emoji: "🔙" },
                { word: "there", phonetic: "/ðeə/", meaning: "那里/表存在", example: "<em>There</em> is a big bed.", emoji: "📍" },
            ]},
            6: { name: "Unit 6 In a nature park", words: [
                { word: "forest", phonetic: "/ˈfɒrɪst/", meaning: "森林", example: "The <em>forest</em> is big.", emoji: "🌲" },
                { word: "lake", phonetic: "/leɪk/", meaning: "湖泊", example: "The <em>lake</em> is beautiful.", emoji: "🏞️" },
                { word: "river", phonetic: "/ˈrɪvə/", meaning: "河流", example: "The <em>river</em> is long.", emoji: "🏞️" },
                { word: "mountain", phonetic: "/ˈmaʊntɪn/", meaning: "高山", example: "The <em>mountain</em> is high.", emoji: "⛰️" },
                { word: "hill", phonetic: "/hɪl/", meaning: "小山丘", example: "Let's climb the <em>hill</em>.", emoji: "🏕️" },
                { word: "tree", phonetic: "/triː/", meaning: "树", example: "The <em>tree</em> is tall.", emoji: "🌳" },
                { word: "bridge", phonetic: "/brɪdʒ/", meaning: "桥", example: "Cross the <em>bridge</em>.", emoji: "🌉" },
                { word: "building", phonetic: "/ˈbɪldɪŋ/", meaning: "建筑物", example: "The <em>building</em> is tall.", emoji: "🏢" },
                { word: "village", phonetic: "/ˈvɪlɪdʒ/", meaning: "村庄", example: "The <em>village</em> is quiet.", emoji: "🏘️" },
                { word: "nature", phonetic: "/ˈneɪtʃə/", meaning: "自然", example: "I love <em>nature</em>.", emoji: "🌿" },
                { word: "boating", phonetic: "/ˈbəʊtɪŋ/", meaning: "划船", example: "Let's go <em>boating</em>.", emoji: "🚣" },
            ]},
        }
    },
    "PEP_5下": {
        name: "五年级下册（人教PEP）",
        grade: 5, semester: "下",
        units: {
            1: { name: "Unit 1 My day", words: [
                { word: "eat breakfast", phonetic: "/iːt ˈbrekfəst/", meaning: "吃早饭", example: "I <em>eat breakfast</em> at 7.", emoji: "🥣" },
                { word: "eat dinner", phonetic: "/iːt ˈdɪnə/", meaning: "吃晚饭", example: "I <em>eat dinner</em> at 6.", emoji: "🍽️" },
                { word: "exercise", phonetic: "/ˈeksəsaɪz/", meaning: "锻炼", example: "I <em>exercise</em> every day.", emoji: "🏃" },
                { word: "go shopping", phonetic: "/ɡəʊ ˈʃɒpɪŋ/", meaning: "购物", example: "Let's <em>go shopping</em>.", emoji: "🛒" },
                { word: "go for a walk", phonetic: "/ɡəʊ fɔːr ə wɔːk/", meaning: "散步", example: "I <em>go for a walk</em> after dinner.", emoji: "🚶" },
                { word: "clean my room", phonetic: "/kliːn maɪ ruːm/", meaning: "打扫房间", example: "I <em>clean my room</em> on weekends.", emoji: "🧹" },
                { word: "when", phonetic: "/wen/", meaning: "什么时候", example: "<em>When</em> do you get up?", emoji: "❓" },
                { word: "after", phonetic: "/ˈɑːftə/", meaning: "在…之后", example: "I read <em>after</em> dinner.", emoji: "⏭️" },
                { word: "start", phonetic: "/stɑːt/", meaning: "开始", example: "Class <em>starts</em> at 8.", emoji: "🏁" },
                { word: "usually", phonetic: "/ˈjuːʒuəli/", meaning: "通常", example: "I <em>usually</em> get up at 7.", emoji: "🔄" },
                { word: "busy", phonetic: "/ˈbɪzi/", meaning: "忙碌的", example: "I am <em>busy</em> today.", emoji: "🐝" },
            ]},
            2: { name: "Unit 2 My favourite season", words: [
                { word: "spring", phonetic: "/sprɪŋ/", meaning: "春天", example: "I like <em>spring</em>.", emoji: "🌸" },
                { word: "summer", phonetic: "/ˈsʌmə/", meaning: "夏天", example: "I swim in <em>summer</em>.", emoji: "☀️" },
                { word: "autumn", phonetic: "/ˈɔːtəm/", meaning: "秋天", example: "<em>Autumn</em> is cool.", emoji: "🍂" },
                { word: "winter", phonetic: "/ˈwɪntə/", meaning: "冬天", example: "It snows in <em>winter</em>.", emoji: "❄️" },
                { word: "season", phonetic: "/ˈsiːzn/", meaning: "季节", example: "What <em>season</em> do you like?", emoji: "🔄" },
                { word: "pick apples", phonetic: "/pɪk ˈæplz/", meaning: "摘苹果", example: "We <em>pick apples</em> in autumn.", emoji: "🍎" },
                { word: "make a snowman", phonetic: "/meɪk ə ˈsnəʊmæn/", meaning: "堆雪人", example: "Let's <em>make a snowman</em>.", emoji: "⛄" },
                { word: "go swimming", phonetic: "/ɡəʊ ˈswɪmɪŋ/", meaning: "去游泳", example: "I <em>go swimming</em> in summer.", emoji: "🏊" },
                { word: "go on a picnic", phonetic: "/ɡəʊ ɒn ə ˈpɪknɪk/", meaning: "去野餐", example: "Let's <em>go on a picnic</em>.", emoji: "🧺" },
                { word: "which", phonetic: "/wɪtʃ/", meaning: "哪一个", example: "<em>Which</em> season do you like?", emoji: "🤔" },
                { word: "because", phonetic: "/bɪˈkɒz/", meaning: "因为", example: "I like spring <em>because</em> of flowers.", emoji: "💡" },
                { word: "vacation", phonetic: "/vəˈkeɪʃn/", meaning: "假期", example: "I like summer <em>vacation</em>.", emoji: "🏖️" },
            ]},
            3: { name: "Unit 3 My school calendar", words: [
                { word: "January", phonetic: "/ˈdʒænjuəri/", meaning: "一月", example: "<em>January</em> is the first month.", emoji: "📅" },
                { word: "February", phonetic: "/ˈfebruəri/", meaning: "二月", example: "<em>February</em> is short.", emoji: "📅" },
                { word: "March", phonetic: "/mɑːtʃ/", meaning: "三月", example: "Tree Day is in <em>March</em>.", emoji: "📅" },
                { word: "April", phonetic: "/ˈeɪprəl/", meaning: "四月", example: "Easter is in <em>April</em>.", emoji: "📅" },
                { word: "May", phonetic: "/meɪ/", meaning: "五月", example: "May Day is in <em>May</em>.", emoji: "📅" },
                { word: "June", phonetic: "/dʒuːn/", meaning: "六月", example: "Children's Day is in <em>June</em>.", emoji: "📅" },
                { word: "July", phonetic: "/dʒuˈlaɪ/", meaning: "七月", example: "<em>July</em> is in summer.", emoji: "📅" },
                { word: "August", phonetic: "/ˈɔːɡəst/", meaning: "八月", example: "<em>August</em> is hot.", emoji: "📅" },
                { word: "September", phonetic: "/sepˈtembə/", meaning: "九月", example: "School starts in <em>September</em>.", emoji: "📅" },
                { word: "October", phonetic: "/ɒkˈtəʊbə/", meaning: "十月", example: "National Day is in <em>October</em>.", emoji: "📅" },
                { word: "November", phonetic: "/nəʊˈvembə/", meaning: "十一月", example: "<em>November</em> is in autumn.", emoji: "📅" },
                { word: "December", phonetic: "/dɪˈsembə/", meaning: "十二月", example: "Christmas is in <em>December</em>.", emoji: "📅" },
            ]},
            4: { name: "Unit 4 When is Easter?", words: [
                { word: "first", phonetic: "/fɜːst/", meaning: "第一", example: "January is the <em>first</em> month.", emoji: "🥇" },
                { word: "second", phonetic: "/ˈsekənd/", meaning: "第二", example: "February is the <em>second</em> month.", emoji: "🥈" },
                { word: "third", phonetic: "/θɜːd/", meaning: "第三", example: "March is the <em>third</em> month.", emoji: "🥉" },
                { word: "fourth", phonetic: "/fɔːθ/", meaning: "第四", example: "My birthday is on the <em>fourth</em>.", emoji: "4️⃣" },
                { word: "fifth", phonetic: "/fɪfθ/", meaning: "第五", example: "May is the <em>fifth</em> month.", emoji: "5️⃣" },
                { word: "twelfth", phonetic: "/twelfθ/", meaning: "第十二", example: "December is the <em>twelfth</em> month.", emoji: "🔢" },
                { word: "twentieth", phonetic: "/ˈtwentiəθ/", meaning: "第二十", example: "My birthday is on the <em>twentieth</em>.", emoji: "🔢" },
                { word: "special", phonetic: "/ˈspeʃl/", meaning: "特殊的", example: "Today is a <em>special</em> day.", emoji: "🎉" },
                { word: "birthday", phonetic: "/ˈbɜːθdeɪ/", meaning: "生日", example: "Happy <em>birthday</em>!", emoji: "🎂" },
                { word: "kitten", phonetic: "/ˈkɪtn/", meaning: "小猫", example: "The <em>kitten</em> is cute.", emoji: "🐱" },
            ]},
            5: { name: "Unit 5 Whose dog is it?", words: [
                { word: "mine", phonetic: "/maɪn/", meaning: "我的", example: "This book is <em>mine</em>.", emoji: "🙋" },
                { word: "yours", phonetic: "/jɔːz/", meaning: "你的", example: "Is this <em>yours</em>?", emoji: "👉" },
                { word: "his", phonetic: "/hɪz/", meaning: "他的", example: "This pen is <em>his</em>.", emoji: "👦" },
                { word: "hers", phonetic: "/hɜːz/", meaning: "她的", example: "The bag is <em>hers</em>.", emoji: "👧" },
                { word: "theirs", phonetic: "/ðeəz/", meaning: "他们的", example: "The toys are <em>theirs</em>.", emoji: "👥" },
                { word: "ours", phonetic: "/ˈaʊəz/", meaning: "我们的", example: "The classroom is <em>ours</em>.", emoji: "👩‍👩‍👧" },
                { word: "climbing", phonetic: "/ˈklaɪmɪŋ/", meaning: "攀爬", example: "The cat is <em>climbing</em>.", emoji: "🧗" },
                { word: "jumping", phonetic: "/ˈdʒʌmpɪŋ/", meaning: "跳跃", example: "The rabbit is <em>jumping</em>.", emoji: "🐰" },
                { word: "eating", phonetic: "/ˈiːtɪŋ/", meaning: "正在吃", example: "The dog is <em>eating</em>.", emoji: "🐕" },
                { word: "sleeping", phonetic: "/ˈsliːpɪŋ/", meaning: "正在睡觉", example: "The baby is <em>sleeping</em>.", emoji: "😴" },
            ]},
            6: { name: "Unit 6 Work quietly!", words: [
                { word: "reading", phonetic: "/ˈriːdɪŋ/", meaning: "正在阅读", example: "She is <em>reading</em> a book.", emoji: "📖" },
                { word: "listening", phonetic: "/ˈlɪsənɪŋ/", meaning: "正在听", example: "He is <em>listening</em> to music.", emoji: "🎧" },
                { word: "playing", phonetic: "/ˈpleɪɪŋ/", meaning: "正在玩", example: "They are <em>playing</em>.", emoji: "🎮" },
                { word: "doing homework", phonetic: "/duːɪŋ ˈhəʊmwɜːk/", meaning: "正在做作业", example: "She is <em>doing homework</em>.", emoji: "📝" },
                { word: "keep", phonetic: "/kiːp/", meaning: "保持", example: "<em>Keep</em> your desk clean.", emoji: "🧹" },
                { word: "quietly", phonetic: "/ˈkwaɪətli/", meaning: "安静地", example: "Please work <em>quietly</em>.", emoji: "🤫" },
                { word: "turn", phonetic: "/tɜːn/", meaning: "轮流/转弯", example: "Take <em>turns</em>.", emoji: "🔄" },
                { word: "talk", phonetic: "/tɔːk/", meaning: "说话", example: "Don't <em>talk</em> in class.", emoji: "🗣️" },
                { word: "walk", phonetic: "/wɔːk/", meaning: "走/散步", example: "Let's <em>walk</em> to school.", emoji: "🚶" },
                { word: "each other", phonetic: "/iːtʃ ˈʌðə/", meaning: "彼此", example: "We help <em>each other</em>.", emoji: "🤝" },
            ]},
        }
    },
    "PEP_6上": {
        name: "六年级上册（人教PEP）",
        grade: 6, semester: "上",
        units: {
            1: { name: "Unit 1 How can I get there?", words: [
                { word: "science", phonetic: "/ˈsaɪəns/", meaning: "科学", example: "I like <em>science</em> class.", emoji: "🔬" },
                { word: "museum", phonetic: "/mjuːˈziːəm/", meaning: "博物馆", example: "Let's visit the <em>museum</em>.", emoji: "🏛️" },
                { word: "post office", phonetic: "/pəʊst ˈɒfɪs/", meaning: "邮局", example: "The <em>post office</em> is near.", emoji: "📮" },
                { word: "bookstore", phonetic: "/ˈbʊkstɔː/", meaning: "书店", example: "I go to the <em>bookstore</em>.", emoji: "📚" },
                { word: "cinema", phonetic: "/ˈsɪnəmə/", meaning: "电影院", example: "Let's go to the <em>cinema</em>.", emoji: "🎬" },
                { word: "hospital", phonetic: "/ˈhɒspɪtl/", meaning: "医院", example: "The <em>hospital</em> is big.", emoji: "🏥" },
                { word: "crossing", phonetic: "/ˈkrɒsɪŋ/", meaning: "十字路口", example: "Turn at the <em>crossing</em>.", emoji: "🚦" },
                { word: "turn", phonetic: "/tɜːn/", meaning: "转弯", example: "<em>Turn</em> left at the corner.", emoji: "↩️" },
                { word: "left", phonetic: "/left/", meaning: "左边", example: "Turn <em>left</em>.", emoji: "⬅️" },
                { word: "straight", phonetic: "/streɪt/", meaning: "笔直地", example: "Go <em>straight</em> ahead.", emoji: "⬆️" },
                { word: "right", phonetic: "/raɪt/", meaning: "右边", example: "Turn <em>right</em>.", emoji: "➡️" },
            ]},
            2: { name: "Unit 2 Ways to go to school", words: [
                { word: "on foot", phonetic: "/ɒn fʊt/", meaning: "步行", example: "I go to school <em>on foot</em>.", emoji: "🚶" },
                { word: "by bus", phonetic: "/baɪ bʌs/", meaning: "乘公交车", example: "I go <em>by bus</em>.", emoji: "🚌" },
                { word: "by plane", phonetic: "/baɪ pleɪn/", meaning: "乘飞机", example: "We go <em>by plane</em>.", emoji: "✈️" },
                { word: "by taxi", phonetic: "/baɪ ˈtæksi/", meaning: "乘出租车", example: "Let's go <em>by taxi</em>.", emoji: "🚕" },
                { word: "by ship", phonetic: "/baɪ ʃɪp/", meaning: "乘船", example: "We travel <em>by ship</em>.", emoji: "🚢" },
                { word: "by subway", phonetic: "/baɪ ˈsʌbweɪ/", meaning: "乘地铁", example: "I go <em>by subway</em>.", emoji: "🚇" },
                { word: "by train", phonetic: "/baɪ treɪn/", meaning: "乘火车", example: "We go <em>by train</em>.", emoji: "🚆" },
                { word: "slow down", phonetic: "/sləʊ daʊn/", meaning: "慢下来", example: "<em>Slow down</em> please.", emoji: "🐢" },
                { word: "stop", phonetic: "/stɒp/", meaning: "停止", example: "<em>Stop</em> at the red light.", emoji: "🛑" },
                { word: "wait", phonetic: "/weɪt/", meaning: "等待", example: "<em>Wait</em> at the yellow light.", emoji: "⏳" },
                { word: "helmet", phonetic: "/ˈhelmɪt/", meaning: "头盔", example: "Wear a <em>helmet</em>.", emoji: "⛑️" },
            ]},
            3: { name: "Unit 3 My weekend plan", words: [
                { word: "visit", phonetic: "/ˈvɪzɪt/", meaning: "拜访/参观", example: "I will <em>visit</em> my grandma.", emoji: "🏠" },
                { word: "film", phonetic: "/fɪlm/", meaning: "电影", example: "Let's see a <em>film</em>.", emoji: "🎬" },
                { word: "trip", phonetic: "/trɪp/", meaning: "旅行", example: "We have a school <em>trip</em>.", emoji: "🧳" },
                { word: "supermarket", phonetic: "/ˈsuːpəmɑːkɪt/", meaning: "超市", example: "I go to the <em>supermarket</em>.", emoji: "🛒" },
                { word: "evening", phonetic: "/ˈiːvnɪŋ/", meaning: "傍晚", example: "I read in the <em>evening</em>.", emoji: "🌆" },
                { word: "tonight", phonetic: "/təˈnaɪt/", meaning: "今晚", example: "What will you do <em>tonight</em>?", emoji: "🌙" },
                { word: "tomorrow", phonetic: "/təˈmɒrəʊ/", meaning: "明天", example: "I will go <em>tomorrow</em>.", emoji: "📅" },
                { word: "next week", phonetic: "/nekst wiːk/", meaning: "下周", example: "I have a test <em>next week</em>.", emoji: "📆" },
                { word: "dictionary", phonetic: "/ˈdɪkʃənəri/", meaning: "字典", example: "I need a <em>dictionary</em>.", emoji: "📕" },
                { word: "comic book", phonetic: "/ˈkɒmɪk bʊk/", meaning: "漫画书", example: "I like <em>comic books</em>.", emoji: " comic" },
                { word: "postcard", phonetic: "/ˈpəʊstkɑːd/", meaning: "明信片", example: "I send a <em>postcard</em>.", emoji: "📮" },
                { word: "word book", phonetic: "/wɜːd bʊk/", meaning: "单词书", example: "I buy a <em>word book</em>.", emoji: "📖" },
            ]},
            4: { name: "Unit 4 I have a pen pal", words: [
                { word: "hobby", phonetic: "/ˈhɒbi/", meaning: "爱好", example: "My <em>hobby</em> is reading.", emoji: "🎯" },
                { word: "reading", phonetic: "/ˈriːdɪŋ/", meaning: "阅读", example: "I like <em>reading</em> books.", emoji: "📖" },
                { word: "hiking", phonetic: "/ˈhaɪkɪŋ/", meaning: "远足", example: "I enjoy <em>hiking</em>.", emoji: "🥾" },
                { word: "puzzle", phonetic: "/ˈpʌzl/", meaning: "拼图/谜", example: "I like doing <em>puzzles</em>.", emoji: "🧩" },
                { word: "dancing", phonetic: "/ˈdɑːnsɪŋ/", meaning: "跳舞", example: "She loves <em>dancing</em>.", emoji: "💃" },
                { word: "singing", phonetic: "/ˈsɪŋɪŋ/", meaning: "唱歌", example: "<em>Singing</em> makes me happy.", emoji: "🎤" },
                { word: "cooking", phonetic: "/ˈkʊkɪŋ/", meaning: "烹饪", example: "I like <em>cooking</em>.", emoji: "🍳" },
                { word: "swimming", phonetic: "/ˈswɪmɪŋ/", meaning: "游泳", example: "<em>Swimming</em> is fun.", emoji: "🏊" },
                { word: "pen pal", phonetic: "/pen pæl/", meaning: "笔友", example: "I have a <em>pen pal</em>.", emoji: "✉️" },
                { word: "also", phonetic: "/ˈɔːlsəʊ/", meaning: "也", example: "I <em>also</em> like singing.", emoji: "➕" },
                { word: "live", phonetic: "/lɪv/", meaning: "居住", example: "I <em>live</em> in China.", emoji: "🏠" },
            ]},
            5: { name: "Unit 5 What does he do?", words: [
                { word: "factory worker", phonetic: "/ˈfæktəri ˈwɜːkə/", meaning: "工厂工人", example: "She is a <em>factory worker</em>.", emoji: "🏭" },
                { word: "postman", phonetic: "/ˈpəʊstmən/", meaning: "邮递员", example: "The <em>postman</em> brings letters.", emoji: "📮" },
                { word: "businessman", phonetic: "/ˈbɪznɪsmæn/", meaning: "商人", example: "My uncle is a <em>businessman</em>.", emoji: "💼" },
                { word: "police officer", phonetic: "/pəˈliːs ˈɒfɪsə/", meaning: "警察", example: "The <em>police officer</em> helps us.", emoji: "👮" },
                { word: "fisherman", phonetic: "/ˈfɪʃəmən/", meaning: "渔民", example: "The <em>fisherman</em> caught a big fish.", emoji: "🎣" },
                { word: "scientist", phonetic: "/ˈsaɪəntɪst/", meaning: "科学家", example: "I want to be a <em>scientist</em>.", emoji: "🧑‍🔬" },
                { word: "pilot", phonetic: "/ˈpaɪlət/", meaning: "飞行员", example: "The <em>pilot</em> flies planes.", emoji: "✈️" },
                { word: "coach", phonetic: "/kəʊtʃ/", meaning: "教练", example: "Our <em>coach</em> is great.", emoji: "🥇" },
                { word: "country", phonetic: "/ˈkʌntri/", meaning: "国家/乡村", example: "I love my <em>country</em>.", emoji: "🗺️" },
                { word: "reporter", phonetic: "/rɪˈpɔːtə/", meaning: "记者", example: "He is a <em>reporter</em>.", emoji: "📰" },
                { word: "writer", phonetic: "/ˈraɪtə/", meaning: "作家", example: "She is a famous <em>writer</em>.", emoji: "✍️" },
            ]},
            6: { name: "Unit 6 How do you feel?", words: [
                { word: "angry", phonetic: "/ˈæŋɡri/", meaning: "生气的", example: "Don't be <em>angry</em>.", emoji: "😠" },
                { word: "afraid", phonetic: "/əˈfreɪd/", meaning: "害怕的", example: "She is <em>afraid</em> of dogs.", emoji: "😨" },
                { word: "worried", phonetic: "/ˈwʌrid/", meaning: "担心的", example: "Mom looks <em>worried</em>.", emoji: "😟" },
                { word: "happy", phonetic: "/ˈhæpi/", meaning: "开心的", example: "I am very <em>happy</em>.", emoji: "😊" },
                { word: "sad", phonetic: "/sæd/", meaning: "难过的", example: "She looks <em>sad</em>.", emoji: "😢" },
                { word: "wear", phonetic: "/weə/", meaning: "穿/戴", example: "I <em>wear</em> a red coat.", emoji: "🧥" },
                { word: "ill", phonetic: "/ɪl/", meaning: "生病的", example: "I am <em>ill</em> today.", emoji: "🤒" },
                { word: "see a doctor", phonetic: "/siː ə ˈdɒktə/", meaning: "看医生", example: "You should <em>see a doctor</em>.", emoji: "🏥" },
                { word: "take a deep breath", phonetic: "/teɪk ə diːp breθ/", meaning: "深呼吸", example: "<em>Take a deep breath</em>.", emoji: "🌬️" },
                { word: "count to ten", phonetic: "/kaʊnt tuː ten/", meaning: "数到十", example: "<em>Count to ten</em> when angry.", emoji: "🔢" },
                { word: "chase", phonetic: "/tʃeɪs/", meaning: "追赶", example: "The cat <em>chases</em> the mouse.", emoji: "🐱" },
            ]},
        }
    },
    "PEP_6下": {
        name: "六年级下册（人教PEP）",
        grade: 6, semester: "下",
        units: {
            1: { name: "Unit 1 How tall are you?", words: [
                { word: "taller", phonetic: "/ˈtɔːlə/", meaning: "更高的", example: "I am <em>taller</em> than you.", emoji: "📏" },
                { word: "shorter", phonetic: "/ˈʃɔːtə/", meaning: "更矮的", example: "She is <em>shorter</em> than me.", emoji: "📐" },
                { word: "longer", phonetic: "/ˈlɒŋɡə/", meaning: "更长的", example: "This snake is <em>longer</em>.", emoji: "🐍" },
                { word: "thinner", phonetic: "/ˈθɪnə/", meaning: "更瘦的", example: "He is <em>thinner</em> than before.", emoji: "🧍" },
                { word: "heavier", phonetic: "/ˈheviə/", meaning: "更重的", example: "The box is <em>heavier</em>.", emoji: "🏋️" },
                { word: "bigger", phonetic: "/ˈbɪɡə/", meaning: "更大的", example: "My room is <em>bigger</em>.", emoji: "📦" },
                { word: "smaller", phonetic: "/ˈsmɔːlə/", meaning: "更小的", example: "This apple is <em>smaller</em>.", emoji: "🍎" },
                { word: "stronger", phonetic: "/ˈstrɒŋɡə/", meaning: "更强壮的", example: "My dad is <em>stronger</em>.", emoji: "💪" },
                { word: "dinosaur", phonetic: "/ˈdaɪnəsɔː/", meaning: "恐龙", example: "The <em>dinosaur</em> is tall.", emoji: "🦕" },
                { word: "shadow", phonetic: "/ˈʃædəʊ/", meaning: "影子", example: "My <em>shadow</em> is long.", emoji: "👥" },
                { word: "metre", phonetic: "/ˈmiːtə/", meaning: "米", example: "I am 1.5 <em>metres</em> tall.", emoji: "📏" },
            ]},
            2: { name: "Unit 2 Last weekend", words: [
                { word: "cleaned", phonetic: "/kliːnd/", meaning: "打扫（过去式）", example: "I <em>cleaned</em> my room.", emoji: "🧹" },
                { word: "washed", phonetic: "/wɒʃt/", meaning: "洗（过去式）", example: "I <em>washed</em> my clothes.", emoji: "🧺" },
                { word: "stayed", phonetic: "/steɪd/", meaning: "停留（过去式）", example: "I <em>stayed</em> at home.", emoji: "🏠" },
                { word: "watched", phonetic: "/wɒtʃt/", meaning: "观看（过去式）", example: "I <em>watched</em> TV.", emoji: "📺" },
                { word: "drank", phonetic: "/dræŋk/", meaning: "喝（过去式）", example: "I <em>drank</em> some tea.", emoji: "🍵" },
                { word: "last weekend", phonetic: "/lɑːst wiːkˈend/", meaning: "上个周末", example: "I played <em>last weekend</em>.", emoji: "📅" },
                { word: "yesterday", phonetic: "/ˈjestədeɪ/", meaning: "昨天", example: "I was busy <em>yesterday</em>.", emoji: "📆" },
                { word: "last night", phonetic: "/lɑːst naɪt/", meaning: "昨晚", example: "I read a book <em>last night</em>.", emoji: "🌙" },
                { word: "magazine", phonetic: "/ˌmæɡəˈziːn/", meaning: "杂志", example: "I read a <em>magazine</em>.", emoji: "📰" },
                { word: "better", phonetic: "/ˈbetə/", meaning: "更好的", example: "I feel <em>better</em> now.", emoji: "😊" },
                { word: "faster", phonetic: "/ˈfɑːstə/", meaning: "更快的", example: "The rabbit is <em>faster</em>.", emoji: "🐇" },
            ]},
            3: { name: "Unit 3 Where did you go?", words: [
                { word: "rode", phonetic: "/rəʊd/", meaning: "骑（过去式）", example: "I <em>rode</em> a bike yesterday.", emoji: "🚲" },
                { word: "went", phonetic: "/went/", meaning: "去（过去式）", example: "I <em>went</em> to the park.", emoji: "🚶" },
                { word: "camping", phonetic: "/ˈkæmpɪŋ/", meaning: "野营", example: "We went <em>camping</em>.", emoji: "⛺" },
                { word: "hurt", phonetic: "/hɜːt/", meaning: "受伤", example: "I <em>hurt</em> my foot.", emoji: "🤕" },
                { word: "ate", phonetic: "/eɪt/", meaning: "吃（过去式）", example: "I <em>ate</em> fresh food.", emoji: "🍽️" },
                { word: "took", phonetic: "/tʊk/", meaning: "拍照（过去式）", example: "I <em>took</em> pictures.", emoji: "📷" },
                { word: "bought", phonetic: "/bɔːt/", meaning: "买（过去式）", example: "I <em>bought</em> some gifts.", emoji: "🎁" },
                { word: "beach", phonetic: "/biːtʃ/", meaning: "海滩", example: "We played on the <em>beach</em>.", emoji: "🏖️" },
                { word: "gift", phonetic: "/ɡɪft/", meaning: "礼物", example: "I bought a <em>gift</em>.", emoji: "🎁" },
                { word: "fell off", phonetic: "/fel ɒf/", meaning: "从…摔下", example: "I <em>fell off</em> my bike.", emoji: "😫" },
            ]},
            4: { name: "Unit 4 Then and now", words: [
                { word: "dining hall", phonetic: "/ˈdaɪnɪŋ hɔːl/", meaning: "食堂", example: "We eat in the <em>dining hall</em>.", emoji: "🍽️" },
                { word: "grass", phonetic: "/ɡrɑːs/", meaning: "草地", example: "Don't walk on the <em>grass</em>.", emoji: "🌱" },
                { word: "gym", phonetic: "/dʒɪm/", meaning: "体育馆", example: "We have a new <em>gym</em>.", emoji: "🏋️" },
                { word: "ago", phonetic: "/əˈɡəʊ/", meaning: "以前", example: "I was short two years <em>ago</em>.", emoji: "⏪" },
                { word: "cycling", phonetic: "/ˈsaɪklɪŋ/", meaning: "骑自行车运动", example: "I like <em>cycling</em>.", emoji: "🚴" },
                { word: "ice-skate", phonetic: "/aɪs skeɪt/", meaning: "滑冰", example: "I learn to <em>ice-skate</em>.", emoji: "⛸️" },
                { word: "badminton", phonetic: "/ˈbædmɪntən/", meaning: "羽毛球", example: "I play <em>badminton</em>.", emoji: "🏸" },
                { word: "star", phonetic: "/stɑː/", meaning: "星星", example: "I can see many <em>stars</em>.", emoji: "⭐" },
                { word: "easy", phonetic: "/ˈiːzi/", meaning: "容易的", example: "This is <em>easy</em>.", emoji: "😊" },
                { word: "Internet", phonetic: "/ˈɪntənet/", meaning: "互联网", example: "I use the <em>Internet</em>.", emoji: "🌐" },
                { word: "different", phonetic: "/ˈdɪfrənt/", meaning: "不同的", example: "Now is <em>different</em> from before.", emoji: "🔄" },
                { word: "active", phonetic: "/ˈæktɪv/", meaning: "积极的/活跃的", example: "She is very <em>active</em>.", emoji: "🏃‍♀️" },
            ]},
        }
    },
};
